// <auto-generated />
using System;
using CAEVSYNC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAEVSYNC.API.Data.Migrations
{
    [DbContext(typeof(CaevsyncDbContext))]
    [Migration("20230427130949_ReformatTransformationSteps2")]
    partial class ReformatTransformationSteps2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAEVSYNC.Data.Entities.AccountToCalendarConnection", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CalendarId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.HasKey("AccountId", "CalendarId");

                    b.HasIndex("CalendarId");

                    b.ToTable("AccountToCalendarConnections");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.Calendar", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.ConnectedAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConnectedAccounts");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationFilterStepData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("BoolFilter")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FromDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntFilter")
                        .HasColumnType("int");

                    b.Property<string>("StringFilter")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ToDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EventTransformationFilterStepData");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationReplaceStepData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("BoolReplacement")
                        .HasColumnType("bit");

                    b.Property<int?>("IntReplacement")
                        .HasColumnType("int");

                    b.Property<string>("StringReplacement")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("EventTransformationReplaceStepData");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationStep", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int>("SyncRuleId")
                        .HasColumnType("int");

                    b.Property<int>("TransformationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SyncRuleId");

                    b.ToTable("EventTransformationSteps");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationTimeExpandStepData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ExtraMinutesAfter")
                        .HasColumnType("int");

                    b.Property<int?>("ExtraMinutesBefore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EventTransformationTimeExpandStepData");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.SyncRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OriginCalendarId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetCalendarId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OriginCalendarId");

                    b.HasIndex("TargetCalendarId");

                    b.ToTable("SyncRules");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.SyncedEventData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventIdInOriginCalendar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventIdInTargetCalendarId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SyncRuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SyncRuleId");

                    b.ToTable("SyncedEventData");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.UserToAccountConnection", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConnectedAccountId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId", "ConnectedAccountId");

                    b.HasIndex("ConnectedAccountId");

                    b.ToTable("UserToAccountConnections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.AccountToCalendarConnection", b =>
                {
                    b.HasOne("CAEVSYNC.Data.Entities.ConnectedAccount", "Account")
                        .WithMany("AccountToCalendarConnections")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAEVSYNC.Data.Entities.Calendar", "Calendar")
                        .WithMany("AccountToCalendarConnections")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationFilterStepData", b =>
                {
                    b.HasOne("CAEVSYNC.Data.Entities.EventTransformationStep", "EventTransformationStep")
                        .WithOne("EventTransformationFilterStepData")
                        .HasForeignKey("CAEVSYNC.Data.Entities.EventTransformationFilterStepData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventTransformationStep");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationReplaceStepData", b =>
                {
                    b.HasOne("CAEVSYNC.Data.Entities.EventTransformationStep", "EventTransformationStep")
                        .WithOne("EventTransformationReplaceStepData")
                        .HasForeignKey("CAEVSYNC.Data.Entities.EventTransformationReplaceStepData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventTransformationStep");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationStep", b =>
                {
                    b.HasOne("CAEVSYNC.Data.Entities.SyncRule", "SyncRule")
                        .WithMany("EventTransformationSteps")
                        .HasForeignKey("SyncRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncRule");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationTimeExpandStepData", b =>
                {
                    b.HasOne("CAEVSYNC.Data.Entities.EventTransformationStep", "EventTransformationStep")
                        .WithOne("EventTransformationTimeExpandStepData")
                        .HasForeignKey("CAEVSYNC.Data.Entities.EventTransformationTimeExpandStepData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventTransformationStep");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.SyncRule", b =>
                {
                    b.HasOne("CAEVSYNC.Data.Entities.Calendar", "OriginCalendar")
                        .WithMany()
                        .HasForeignKey("OriginCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CAEVSYNC.Data.Entities.Calendar", "TargetCalendar")
                        .WithMany()
                        .HasForeignKey("TargetCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginCalendar");

                    b.Navigation("TargetCalendar");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.SyncedEventData", b =>
                {
                    b.HasOne("CAEVSYNC.Data.Entities.SyncRule", "SyncRule")
                        .WithMany()
                        .HasForeignKey("SyncRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncRule");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.UserToAccountConnection", b =>
                {
                    b.HasOne("CAEVSYNC.Data.Entities.ConnectedAccount", "ConnectedAccount")
                        .WithMany("UserToAccountConnections")
                        .HasForeignKey("ConnectedAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectedAccount");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.Calendar", b =>
                {
                    b.Navigation("AccountToCalendarConnections");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.ConnectedAccount", b =>
                {
                    b.Navigation("AccountToCalendarConnections");

                    b.Navigation("UserToAccountConnections");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.EventTransformationStep", b =>
                {
                    b.Navigation("EventTransformationFilterStepData");

                    b.Navigation("EventTransformationReplaceStepData");

                    b.Navigation("EventTransformationTimeExpandStepData");
                });

            modelBuilder.Entity("CAEVSYNC.Data.Entities.SyncRule", b =>
                {
                    b.Navigation("EventTransformationSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
